\i CREATION/triggers/create_triggers_artiste.sql
\i CREATION/triggers/creation_triggers_lieu.sql
\i CREATION/triggers/create_triggers_concert.sql
\i CREATION/triggers/create_triggers_utilisateur.sql
\i CREATION/triggers/create_triggers_al.sql
\i CREATION/triggers/create_triggers_attendre.sql
\i CREATION/triggers/create_triggers_billet.sql
\i CREATION/triggers/create_triggers_categorie.sql
\i CREATION/triggers/create_triggers_grille.sql
\i CREATION/triggers/create_triggers_siege.sql
\i CREATION/triggers/create_triggers_sv.sql